global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus scrapes itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  # Node Exporter targets
  # Add servers like: 192.168.0.79:9100, 192.168.0.50:9100 etc
  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "YOUR_SERVER_IP:9100"

